mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('account/', include('users.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('polls/<int:question_id>/',
         login_required(views.DetailView.as_view()), name='detail'),
    path('polls/<int:pk>/results/',
         login_required(views.ResultsView.as_view()), name='results'),
    path('polls/<int:question_id>/vote/',
         login_required(views.VoteView.as_view()), name='vote'),

    path('polls/api/', include('polls.api.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/api/urls.py
from django.urls import include, path

app_name = 'api'
urlpatterns = [
    path('v1/', include('users.api.v1.urls'))
]

users/urls.py
from django.urls import path, reverse_lazy, include
from .views import SignUpView, ChangePasswordView, ActivateAccount
from django.contrib.auth import views as auth_views
from .forms import CustomPasswordChangeForm, CustomAuthenticationForm

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(),
         name='activate'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html',
        authentication_form=CustomAuthenticationForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('change-password/', ChangePasswordView.as_view(),
         name='change_password'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        form_class=CustomPasswordChangeForm,
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('api/', include('users.api.urls')),

]

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _


class CustomUserManager(BaseUserManager):
    """
    Overriding the BaseUserManager to ask for email and password rather the
    default username & password during-
    user/superuser creation.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Creates and saves a SuperUser with the given email and password.Also
        sets default permissions to the superuser.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Creating a custom User class MyUser that subclasses AbstractUser,
    extending the default fields and
    setting the new unique identifier for the user model to 'email'.
    """
    username = None
    email = models.EmailField(
        verbose_name='email address', max_length=255, unique=True)

    date_of_birth = models.DateField(null=True, default=None, blank=True)
    image = models.ImageField(
        null=True, upload_to='profile_pics', blank=True)
    nickname = models.CharField(max_length=200, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def image_tag(self):
        """
        A method to display the user image on the admin list_display.
        """
        if self.image:
            return format_html('<img src="{}" width="100px" height="100px" />'.
                               format(self.image.url))

    image_tag.allow_tags = True
    image_tag.short_description = 'Image'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, AuthenticationForm
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('email', 'first_name', 'last_name',)

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        query = User.objects.filter(email=email)
        if query.exists():
            raise forms.ValidationError("Email is taken")
        return email


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',)


class CustomPasswordChangeForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email=email).exists():
            raise ValidationError("Email does not exist")
        elif not User.objects.get(email=email).is_active:
            raise ValidationError("This account has not been verified")

        return email


class CustomAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise ValidationError("This account has not been verified!")

users/api/v1/views.py
from rest_framework import generics
from .serializers import UserSerializer
from django.contrib.auth import get_user_model

User = get_user_model()


class UserViewSet(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetailView(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

users/views.py
from django.views.generic.edit import FormMixin, CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.views import View
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login, get_user_model
from django.contrib.messages.views import SuccessMessageMixin

User = get_user_model()


class SignUpView(CreateView):
    template_name = 'users/signup.html'
    form_class = CustomUserCreationForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def send_user_verification_mail(self, request, user):
        current_site = get_current_site(request)
        subject = 'Activate your polls account'
        message = render_to_string('users/account_activation_email.html', {
            'users': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        user.email_user(subject, message)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            self.send_user_verification_mail(request, user)

            messages.success(request,
                             'Please confirm your email to complete '
                             'registration.')

            return redirect('users:login')

        return render(request, self.template_name, {'form': form})


class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)

        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user,
                                                                     token):
            user.is_active = True
            user.save()
            # login(request, user) for the user to be logged in after verifying
            messages.success(request, 'Your account has been verified')
            return redirect('users:login')

        else:
            messages.warning(request,
                             "Confirmation link invalid, please verify "
                             "that the link hasn't been used before.")
            return redirect('polls:index')


class ChangePasswordView(SuccessMessageMixin, auth_views.PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Your password has been changed!"
    success_url = reverse_lazy('polls:index')

users/templates/users/account_activation_email.html
{% autoescape off %}
Hi, {{ user.get_first_name }}

Please click on the link below to complete your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/change_password.html
{% load crispy_forms_tags %}
<form method="POST">
    {% csrf_token %}

    <h2>Change Password</h2><br>

    <fieldset >
        {{ form|crispy }}
    </fieldset> <br>
        <button type="submit">Confirm</button>
</form>

users/templates/users/login.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log In</title>
</head>
<body>
<h2>Log In</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Log In</button>
    <br><br>
    <small>
        <a href="{% url 'users:password_reset' %}">Forgot your password?</a>
    </small>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class=" {{ message.tags }}" {% endif %} >{{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
</form>
</body>
</html>

users/templates/users/password_reset.html
<form method="POST">
    {% csrf_token %}

    <h2>Reset Password</h2><br>

    <fieldset >
        {{ form }}
    </fieldset> <br>
        <button type="submit">Request Password Reset</button>
</form>

users/templates/users/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Your password has been set.</h2>
    <br><br>
    <a href="{% url 'users:login' %}">Sign In Here</a>
</body>
</html>

users/templates/users/password_reset_confirm.html
{% load crispy_forms_tags %}
<form method="POST">
    {% csrf_token %}

    <h2>Reset Password</h2><br>

    <fieldset>
        {{ form|crispy }}
    </fieldset> <br>
        <button type="submit">Reset Password</button>
</form>

users/templates/users/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>An email has been sent to reset your password!</h2>
</body>
</html>

users/templates/users/password_reset_email.html
{% autoescape off %}
Hello,
We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.
If you did not make this request, you can simply ignore this email.
Sincerely,
The Website Team
{% endautoescape %}

users/templates/users/signup.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Sign Up</button>
</form>
</body>
</html>